services:
  api-test:
    build: 
      context: .
      dockerfile: backend/dockerfile.test
    container_name: test_api
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - /app/backend/node_modules
      - /app/shared/node_modules
    environment:
      - NODE_ENV=test
    command: npm test

  # Dedicated target for only running unit tests
  api-test-unit:
    extends: api-test
    container_name: test_api_unit
    command: npm run test:unit
  
  # Dedicated target for only running integration tests
  api-test-integration:
    extends: api-test
    container_name: test_api_integration
    command: npm run test:integration

# Full Docker command to run for tests
# docker compose -f docker-compose.test.yml run --rm api-test-integration 