services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=dev
      - PORT=3000
  api-test:
    build: .
    container_name: test_api
    environment:
      - NODE_ENV=test
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm test