FROM node:22-alpine

WORKDIR /app

COPY backend/package*.json ./backend/
COPY shared/package*.json ./shared/

WORKDIR /app/backend
RUN npm ci

WORKDIR /app/shared
RUN npm ci

COPY backend ./backend
COPY shared ./shared

WORKDIR /app/backend

CMD ["npm", "test"]