name: CI

on:
    pull_request:
        branches: 
            - "**"
    
    push:
        branches: 
            - "**"

concurrency:
    group: ci-${{ github.ref }} 
    cancel-in-progress: true   

jobs:

    unit-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Create test env
              run: |
                cat > backend/.env.test <<EOF
                PORT=3000
                NODE_ENV=test
                TEST_DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}
                JWT_SECRET=${{ secrets.JWT_SECRET }}
                APP_MAILER_HOST=${{ secrets.APP_MAILER_HOST }}
                APP_MAILER_PORT=${{ secrets.APP_MAILER_PORT }}
                GOOGLE_APP_PASSWORD=${{ secrets.GOOGLE_APP_PASSWORD }}
                APP_MAILER=${{ secrets.APP_MAILER }}
                FOOD_DATA_API_KEY=${{ secrets.FOOD_DATA_API_KEY }}
                WORKOUT_DATA_API_KEY=${{ secrets.WORKOUT_DATA_API_KEY }}
                EOF

            - name: Build containers
              run: docker compose -f docker-compose.test.yml build

            - name: Run unit tests
              run: docker compose -f docker-compose.test.yml run --rm api-test-unit

    integration-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Create test env
              run: |
                cat > backend/.env.test <<EOF
                PORT=3000
                NODE_ENV=test
                TEST_DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}
                JWT_SECRET=${{ secrets.JWT_SECRET }}
                APP_MAILER_HOST=${{ secrets.APP_MAILER_HOST }}
                APP_MAILER_PORT=${{ secrets.APP_MAILER_PORT }}
                GOOGLE_APP_PASSWORD=${{ secrets.GOOGLE_APP_PASSWORD }}
                APP_MAILER=${{ secrets.APP_MAILER }}
                FOOD_DATA_API_KEY=${{ secrets.FOOD_DATA_API_KEY }}
                WORKOUT_DATA_API_KEY=${{ secrets.WORKOUT_DATA_API_KEY }}
                EOF

            - name: Build containers
              run: docker compose -f docker-compose.test.yml build
            
            - name: Run integration tests
              run: docker compose -f docker-compose.test.yml run --rm api-test-integration

            - name: Cleanup
              if: always()
              run: docker compose -f docker-compose-test.yml down -v
        