name: Release

on:
    push:
        branches:
            - master

jobs:
    verify:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Create test env
              run: |
                cat <<EOF > backend/.env.test
                PORT=3000
                NODE_ENV=test
                TEST_DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}
                JWT_SECRET=${{ secrets.JWT_SECRET }}
                APP_MAILER_HOST=${{ secrets.APP_MAILER_HOST }}
                APP_MAILER_PORT=${{ secrets.APP_MAILER_PORT }}
                GOOGLE_APP_PASSWORD=${{ secrets.GOOGLE_APP_PASSWORD }}
                APP_MAILER=${{ secrets.APP_MAILER }}
                FOOD_DATA_API_KEY=${{ secrets.FOOD_DATA_API_KEY }}
                WORKOUT_DATA_API_KEY=${{ secrets.WORKOUT_DATA_API_KEY }}
                EOF

            - name: Run unit tests
              run: docker compose -f docker-compose.test.yml run --rm api-test-unit

            - name: Run integration test
              run: docker compose -f docker-compose.test.yml run --rm api-test-integration

            - name: Cleanup
              if: always()
              run: docker compose -f docker-compose.test.yml down -v

    docker:
        needs: verify

        runs-on: ubuntu-latest

        permissions:
            packages: write
            contents: read

        steps:
            - uses: actions/checkout@v4

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

              # Allows docker to read repo in lowerase, since images dont accept uppercase
            - name: Set lowercase image name
              run: echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
        
            - name: Build backend image
              run: |
                docker build \
                -t ghcr.io/${{ env.IMAGE_NAME }}/backend:latest \
                -f backend/Dockerfile \
                .
            - name: Build frontend image
              run: |
                docker build  \
                -t ghcr.io/${{ env.IMAGE_NAME }}/frontend:latest  \
                -f frontend/dockerfile \
                .
            - name: Push backend image
              run: |
                docker push ghcr.io/${{ env.IMAGE_NAME }}/backend:latest
            
            - name: Push frontend image
              run: |
                docker push ghcr.io/${{ env.IMAGE_NAME }}/frontend:latest
